services:
  hoarder:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    container_name: hoarder
    volumes:
      - ~/volumes/hoarder:/data
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://hoarder-meilisearch:7700
      BROWSER_WEB_URL: http://hoarder-chrome:9222
      DATA_DIR: /data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoarder.rule=Host(`${HOARDER_ENDPOINT_URL}`)"
      - "traefik.http.routers.hoarder.entrypoints=hoarder"
      - "traefik.http.services.hoarder.loadbalancer.server.port=3000"
      - "homepage.group=Web"
      - "homepage.name=Hoarder"
      - "homepage.icon=karakeep.svg"
      - "homepage.href=https://${HOARDER_ENDPOINT_URL}"
      - "homepage.description=Bookmark manager with a focus on privacy and security."
    depends_on:
      - hoarder-chrome
      - hoarder-meilisearch
      - traefik
    networks:
      - frontend
  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    container_name: hoarder-chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - frontend
  hoarder-meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    container_name: hoarder-meilisearch
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ~/volumes/meili:/meili_data
    networks:
      - frontend
