version: "3"

include:
  - compose/changedetection.yaml
  - compose/duckdns.yaml
  - compose/freshrss.yaml
  - compose/mealie.yaml
  - compose/redlib/redlib.yaml
  - compose/ryot.yaml
  - compose/ttrss.yaml
  - compose/vikunja/vikunja.yaml
  - compose/watchtower.yaml

services:
  traefik:
    image: traefik:v2.0
    container_name: traefik
    command:
#      - --log.level=DEBUG
      - --api=true
      - --api.dashboard=true
      - --providers.docker
      - --providers.file.filename=/config/dynamic.yml
      - --entryPoints.webSecure.address=:443
      - --entryPoints.ttrss.address=:${PORT_TTRSS}
      - --entryPoints.freshrss.address=:${PORT_FRESHRSS}
      - --entryPoints.ryot.address=:${PORT_RYOT}
      - --entryPoints.mealie.address=:${PORT_MEALIE}
      - --entryPoints.changedetection.address=:${PORT_CHANGEDETECTION}
      - --entryPoints.redlib.address=:${PORT_REDLIB}
      - --entryPoints.traefik.address=:${PORT_DASHBOARD}
      - --entryPoints.vikunja.address=:${PORT_VIKUNJA}
      - --entryPoints.homeassistant.address=:${PORT_HOMEASSISTANT}
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=${NETWORK_NAME}
      - --certificatesResolvers.le.acme.email=kwbmm@${URL}
      - --certificatesResolvers.le.acme.tlsChallenge=true
      - --certificatesResolvers.le.acme.dnsChallenge=true
      - --certificatesResolvers.le.acme.dnsChallenge.provider=duckdns
      # Staging server, test purposes only
#      - --certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.le.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.le.acme.storage=/letsencrypt/acme.json
    environment:
      - DUCKDNS_TOKEN=${DDNS_TOKEN}
    ports:
      # The Web UI
      - "${PORT_DASHBOARD}:${PORT_DASHBOARD}"
      # For certificates renewal
      - "443:443"
      # TTRSS
      - "${PORT_TTRSS}:${PORT_TTRSS}"
      # FRESHRSS
      - "${PORT_FRESHRSS}:${PORT_FRESHRSS}"
      # RYOT
      - "${PORT_RYOT}:${PORT_RYOT}"
      - "${PORT_CHANGEDETECTION}:${PORT_CHANGEDETECTION}"
      - "${PORT_MEALIE}:${PORT_MEALIE}"
      - "${PORT_REDLIB}:${PORT_REDLIB}"
      - "${PORT_VIKUNJA}:${PORT_VIKUNJA}"
      - "${PORT_HOMEASSISTANT}:${PORT_HOMEASSISTANT}"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/volumes/traefik-letsencrypt:/letsencrypt
      - ~/volumes/traefik/dynamic.yml:/config/dynamic.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${IP_ADDRESS}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=traefik"
      - "traefik.http.routers.api.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_USR}:${BASIC_AUTH_PSW}"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
