services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    env_file: .vikunja.env
    volumes: 
      - ~/volumes/vikunja:/app/vikunja/files
    depends_on:
      - vikunja-db
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.rule=Host(`${IP_ADDRESS}`)"
      - "traefik.http.routers.vikunja.entrypoints=vikunja"
      - homepage.group=Productivity
      - homepage.name=Vikunja
      - homepage.icon=vikunja.svg
      - homepage.href=http://${IP_ADDRESS}:${PORT_VIKUNJA}
      - homepage.description=TODO app.
    networks:
      - frontend
      - backend

  vikunja-db:
    image: postgres:16-alpine3.19
    container_name: vikunja-db
    environment:
      POSTGRES_PASSWORD: vikunja
      POSTGRES_USER: vikunja
    volumes:
      - ~/volumes/vikunja-db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s