services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - TOKEN=${DDNS_TOKEN}
      - SUBDOMAINS=${DDNS_DOMAINS}
      - TZ=Europe/Paris
    restart: unless-stopped
