services:
  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ~/volumes/freshrss/data:/var/www/FreshRSS/data
      - ~/volumes/freshrss/extensions:/var/www/FreshRSS/extensions
    depends_on:
      - traefik
      - duckdns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.rule=Host(`${IP_ADDRESS}`)"
      - "traefik.http.routers.freshrss.entrypoints=freshrss"
    environment:
      TZ: Europe/Rome
      CRON_MIN: '3,33'
    networks:
      - frontend
      - backend
