services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ~/volumes/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${IP_ADDRESS}:${PORT_HOMEPAGE} # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${IP_ADDRESS}`)"
      - "traefik.http.routers.homepage.entrypoints=homepage"
    networks:
      - frontend

