services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.2.0 
    container_name: mealie
    deploy:
      resources:
        limits:
          memory: 1000M 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`${IP_ADDRESS}`)"
      - "traefik.http.routers.mealie.entrypoints=mealie"
      - homepage.group=Misc
      - homepage.name=Mealie
      - homepage.icon=mealie.svg
      - homepage.href=http://${IP_ADDRESS}:${PORT_MEALIE}
      - homepage.description=Food recipe.
    depends_on:
      - mealie-db
      - traefik
    volumes:
      - ~/volumes/mealie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie-db
      - POSTGRES_PASSWORD=mealie-db
      - POSTGRES_SERVER=mealie-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie-db
    restart: unless-stopped
    networks:
      - frontend
      - backend
  mealie-db:
    container_name: mealie-db
    image: postgres:15.10-alpine3.19
    restart: unless-stopped
    volumes:
      - ~/volumes/mealie-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie-db
      POSTGRES_USER: mealie-db
    networks:
      - backend