services:
  ryot-db:
    image: postgres:16-alpine
    container_name: ryot-db
    volumes:
      - ~/volumes/ryot-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
    restart: unless-stopped

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    container_name: ryot
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - USERS_ALLOW_REGISTRATION=false
    restart: unless-stopped
    depends_on:
      - ryot-db
      - traefik
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ryot.rule=Host(`${IP_ADDRESS}`)"
      - "traefik.http.routers.ryot.entrypoints=ryot"
      - "traefik.http.services.ryot.loadbalancer.server.port=8000"
      - homepage.group=Misc
      - homepage.name=Ryot
      - homepage.icon=ryot.png
      - homepage.href=http://${IP_ADDRESS}:${PORT_RYOT}
      - homepage.description=TV series tracker.
