services:
  ttrss:
    image: nventiveux/ttrss:latest
    container_name: ttrss
    environment:
      - TTRSS_SELF_URL_PATH=https://${URL}:${PORT_TTRSS}
      - TTRSS_DB_HOST=ttrss-db
      - TTRSS_DB_TYPE=pgsql
      - TTRSS_DB_USER=ttrss
      - TTRSS_DB_PASS=ttrss
    volumes:
      - ~/volumes/ttrss-plugins:/srv/ttrss/plugins.local
    restart: unless-stopped
    depends_on:
      - ttrss-db
      - traefik
      - duckdns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ttrss.rule=Host(`${URL}`)"
      - "traefik.http.routers.ttrss.entrypoints=ttrss"
      - "traefik.http.middlewares.secureRedirectTTRss.redirectscheme.scheme=https"
      - "traefik.http.middlewares.secureRedirectTTRss.redirectscheme.port=${PORT_TTRSS}"
      - "traefik.http.routers.ttrss.middlewares=secureRedirectTTRss"
      - "traefik.http.routers.ttrss-sec.tls=true"
      - "traefik.http.routers.ttrss-sec.rule=Host(`${URL}`)"
      - "traefik.http.routers.ttrss-sec.entrypoints=ttrss"
      - "traefik.http.routers.ttrss-sec.tls.certResolver=le"
    networks:
      - frontend
      - backend
  ttrss-db:
    image: postgres:14-alpine3.19
    container_name: ttrss-db
    environment:
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
    volumes:
      - ~/volumes/ttrss-db:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
