services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${WATCHTOWER_TG_API_TOKEN}@telegram?channels=${WATCHTOWER_TG_CHANNEL_ID}&title=Watchtower
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=28800
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  